import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createClient} from '@supabase/supabase-js';
import {academicYears,starterCourses,starterSessions} from './data.js';
import {LayoutDashboard,CalendarDays,BookOpen,CalendarRange,ClipboardList,Plus,Check,Clock,MapPin,Bell,ChevronLeft,ChevronRight,Trash2,Pencil,LogOut,X,GraduationCap,ExternalLink,Menu,Mail,Sparkles,Moon,Sun} from 'lucide-react';

const url=import.meta.env.VITE_SUPABASE_URL,key=import.meta.env.VITE_SUPABASE_ANON_KEY;
const db=url&&key?createClient(url,key):null;
const empty={courses:[],class_sessions:[],tasks:[],events:[]};
const nav=[['home','Today',LayoutDashboard],['week','Timetable',CalendarDays],['courses','Courses',BookOpen],['year','Year calendar',CalendarRange],['planner','Planner',ClipboardList]];
const weekdays=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
const tz='Asia/Kuala_Lumpur';
function dateKey(d=new Date()){return new Date(d.getTime()+8*3600000).toISOString().slice(0,10);}
function nextDay(key,n=1){const d=new Date(`${key}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);}
function malaysiaDate(value){const parts=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(value)).filter(p=>p.type!=='literal').map(p=>[p.type,p.value]));return `${parts.year}-${parts.month}-${parts.day}`;}
function malaysiaInput(value){if(!value)return '';const parts=new Intl.DateTimeFormat('sv-SE',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(value));return parts.replace(' ','T');}
function niceDate(k){return new Intl.DateTimeFormat('en-MY',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}).format(new Date(`${k}T12:00:00Z`));}
function formatTime(s){return new Date(`2000-01-01T${s.slice(0,5)}:00+08:00`).toLocaleTimeString('en-MY',{hour:'numeric',minute:'2-digit',hour12:true,timeZone:tz});}
function countdown(starts,now){let mins=Math.max(0,Math.ceil((new Date(starts).getTime()-now)/60000));if(mins===0)return 'Starting now';let days=Math.floor(mins/1440),hours=Math.floor(mins%1440/60);return days?`${days}d ${hours}h left`:hours?`${hours}h ${mins%60}m left`:`${mins}m left`;}
function tone(course){return course?.color||'#cde9dc';}
export function groupSessions(sessions){
  const groups=new Map();
  for(const item of sessions){const key=`${item.day_of_week}:${item.course_id}`;if(!groups.has(key))groups.set(key,{key,course_id:item.course_id,day_of_week:item.day_of_week,items:[]});groups.get(key).items.push(item);}
  return [...groups.values()].map(group=>({...group,items:group.items.sort((a,b)=>a.start_time.localeCompare(b.start_time))})).sort((a,b)=>a.items[0].start_time.localeCompare(b.items[0].start_time));
}
export function distinctSlots(items){const slots=new Map();for(const item of items){const key=`${item.start_time}:${item.end_time}:${item.venue}`;if(!slots.has(key))slots.set(key,{...item,notes:[]});if(item.note&&!slots.get(key).notes.includes(item.note))slots.get(key).notes.push(item.note);}return [...slots.values()];}
function DemoData(){const cached=localStorage.getItem('paper-plan-demo');if(cached){try{return JSON.parse(cached)}catch{}}
  const courses=starterCourses.map((c,i)=>({...c,id:`sample-${i}`,user_id:'demo'}));
  return {courses,class_sessions:starterSessions.map((s,i)=>({...s,id:`class-${i}`,course_id:courses.find(c=>c.code===s.code)?.id,user_id:'demo'})),tasks:[],events:[]};}

export default function App(){
  const [session,setSession]=useState(db?undefined:{user:{id:'demo',email:'demo@local'}});
  const [data,setData]=useState(db?empty:DemoData);
  const [tab,setTab]=useState('home'),[modal,setModal]=useState(null),[year,setYear]=useState(2026),[day,setDay]=useState(dateKey());
  const [now,setNow]=useState(Date.now()),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[menu,setMenu]=useState(false);
  const [theme,setTheme]=useState(()=>{try{return localStorage.getItem('paper-plan-theme')==='dark'?'dark':'light'}catch{return 'light'}});
  const seeding=useRef(false);
  useEffect(()=>{document.documentElement.dataset.theme=theme;try{localStorage.setItem('paper-plan-theme',theme)}catch{}},[theme]);
  const toggleTheme=()=>setTheme(old=>old==='dark'?'light':'dark');
  useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),30000);return()=>clearInterval(timer)},[]);
  useEffect(()=>{if(!db)return;db.auth.getSession().then(({data})=>setSession(data.session));const {data:{subscription}}=db.auth.onAuthStateChange((_evt,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);
  useEffect(()=>{if(db||!session)return;localStorage.setItem('paper-plan-demo',JSON.stringify(data))},[data,session]);
  async function load(user){if(!db||!user||seeding.current)return;setBusy(true);
    try{
      const tables=['courses','class_sessions','tasks','events'];
      const results=await Promise.all(tables.map(t=>db.from(t).select('*').eq('user_id',user.id)));
      const err=results.find(r=>r.error)?.error;if(err)throw err;
      const next=Object.fromEntries(tables.map((t,i)=>[t,results[i].data||[]]));
      const {data:settings,error:settingsError}=await db.from('organizer_settings').select('initialized').eq('user_id',user.id).maybeSingle();if(settingsError)throw settingsError;
      if(!settings?.initialized&&!next.courses.length){
        seeding.current=true;
        const {data:created,error}=await db.from('courses').upsert(starterCourses.map(c=>({...c,user_id:user.id})),{onConflict:'user_id,code'}).select();if(error)throw error;
        next.courses=created;
        if(!next.class_sessions.length){const {data:classes,error:e}=await db.from('class_sessions').insert(starterSessions.map(s=>({user_id:user.id,course_id:created.find(c=>c.code===s.code)?.id,day_of_week:s.day_of_week,start_time:s.start_time,end_time:s.end_time,venue:s.venue,note:s.note}))).select();if(e)throw e;next.class_sessions=classes;}
      }
      if(!settings?.initialized){const {error:initError}=await db.from('organizer_settings').upsert({user_id:user.id,initialized:true});if(initError)throw initError;}
      setData(next);
    }catch(e){setMessage(e.message||'Could not load your organizer. Check the database setup.')}finally{seeding.current=false;setBusy(false)}
  }
  useEffect(()=>{if(!db||!session?.user){if(db)setData(empty);return}load(session.user);
    const channel=db.channel(`organizer-${session.user.id}`);
    ['courses','class_sessions','tasks','events'].forEach(table=>channel.on('postgres_changes',{event:'*',schema:'public',table,filter:`user_id=eq.${session.user.id}`},()=>load(session.user)));
    channel.subscribe();return()=>{db.removeChannel(channel)};
  },[session?.user?.id]);
  function flash(text){setMessage(text);setTimeout(()=>setMessage(''),4500)}
  async function save(table,values,id){setBusy(true);try{
    const payload={...values,user_id:session.user.id};let record;
    if(db){const q=id?db.from(table).update(payload).eq('id',id):db.from(table).insert(payload);const {data:row,error}=await q.select().single();if(error)throw error;record=row;
      setData(old=>({...old,[table]:id?old[table].map(x=>x.id===id?record:x):[...old[table],record]}));
    }else{record={...payload,id:id||crypto.randomUUID(),created_at:new Date().toISOString()};setData(old=>({...old,[table]:id?old[table].map(x=>x.id===id?record:x):[...old[table],record]}));}
    setModal(null);flash('Saved');
  }catch(e){flash(e.message||'Could not save')}finally{setBusy(false)}}
  async function remove(table,item){if(!confirm(`Delete ${item.title||item.name||item.code}?`))return;
    if(db){const {error}=await db.from(table).delete().eq('id',item.id);if(error){flash(error.message);return}}
    setData(old=>{let next={...old,[table]:old[table].filter(x=>x.id!==item.id)};if(table==='courses'){next.class_sessions=next.class_sessions.filter(x=>x.course_id!==item.id);next.tasks=next.tasks.map(x=>x.course_id===item.id?{...x,course_id:null}:x);next.events=next.events.map(x=>x.course_id===item.id?{...x,course_id:null}:x)}return next});flash('Deleted');}
  async function toggle(table,item){const completed=!item.completed;if(db){const {error}=await db.from(table).update({completed}).eq('id',item.id);if(error){flash(error.message);return}}setData(old=>({...old,[table]:old[table].map(x=>x.id===item.id?{...x,completed}:x)}));}
  const courses=useMemo(()=>Object.fromEntries(data.courses.map(c=>[c.id,c])),[data.courses]);
  const eventsFor=k=>data.events.filter(e=>malaysiaDate(e.starts_at)===k).sort((a,b)=>a.starts_at.localeCompare(b.starts_at));
  const tasksFor=k=>data.tasks.filter(t=>t.due_date===k).sort((a,b)=>a.completed-b.completed);
  const thisDay=new Date(`${day}T12:00:00Z`).getUTCDay()||7;
  const today=dateKey(new Date(now));
  const groupedSchedule=useMemo(()=>groupSessions(data.class_sessions),[data.class_sessions]);
  const upcoming=data.events.filter(e=>!e.completed&&new Date(e.starts_at).getTime()>=now).sort((a,b)=>a.starts_at.localeCompare(b.starts_at)).slice(0,4);
  useEffect(()=>{if(!('Notification' in window)||Notification.permission!=='granted')return;for(const e of data.events){if(e.completed||new Date(e.starts_at).getTime()<=now)continue;const h=(new Date(e.starts_at).getTime()-now)/3600000;const steps=[336,168,72,48,...Array.from({length:24},(_,i)=>24-i)];const step=steps.find(x=>h<=x&&h>x-0.04);if(!step)continue;const flag=`paper-plan-alert-${e.id}-${e.starts_at}-${step}`;if(localStorage.getItem(flag))continue;localStorage.setItem(flag,'1');new Notification(`${e.kind}: ${e.title}`,{body:`${Math.round(step)} hours until it begins · ${e.venue||'See your organizer'}`})}},[now,data.events]);

  if(session===undefined)return <div className="center-screen">Opening your planner…</div>;
  if(!session)return <Auth onMessage={flash} message={message} theme={theme} onToggleTheme={toggleTheme}/>;
  return <div className="app-shell">
    <aside className={`sidebar ${menu?'show':''}`}><div className="brand"><span className="brand-mark"><GraduationCap size={22}/></span><span>paper<span className="pink">plan.</span><small>my study space</small></span></div>
      <div className="side-label">MY SPACE</div><nav aria-label="Main navigation">{nav.map(([id,label,Icon])=><button key={id} className={`nav-link ${tab===id?'active':''}`} onClick={()=>{setTab(id);setMenu(false)}}><Icon size={19} strokeWidth={1.9}/>{label}</button>)}</nav>
      <div className="sidebar-bottom"><div className="side-note"><div className="tape"></div><span>One thing at a time.<br/>You’ve got this.</span></div><div className="account"><div className="avatar">{session.user.email?.[0]?.toUpperCase()||'P'}</div><span title={session.user.email}>{db?session.user.email:'Preview mode'}<small>{db?'Synced across devices':'Saved on this device'}</small></span>{db&&<button className="icon-button" title="Sign out" onClick={()=>db.auth.signOut()}><LogOut size={17}/></button>}</div></div>
    </aside>
    <main className="main-area"><header className="topbar"><button className="icon-button mobile-menu" onClick={()=>setMenu(!menu)} aria-label="Menu"><Menu size={22}/></button><span>YOUR LITTLE CORNER TO GET THINGS DONE</span><div className="topbar-actions"><button className="icon-button theme-toggle" onClick={toggleTheme} aria-label={`Switch to ${theme==='dark'?'light':'dark'} mode`} title={`Switch to ${theme==='dark'?'light':'dark'} mode`}>{theme==='dark'?<Sun size={19}/>:<Moon size={19}/>}</button><span className="today-pill"><span className="dot"/>{niceDate(today)}</span></div></header>
      {!db&&<div className="preview-banner"><Bell size={16}/> Preview mode: connect Supabase and Resend to sync devices and email reminders.</div>}
      {message&&<div role="status" className="toast">{message}</div>}
      {tab==='home'&&<><section className="page-heading"><div><div className="eyebrow">THE DAILY PAGE</div><h1>Your day, <em>your pace.</em></h1><p>Classes, things to finish, and what comes next.</p></div><button className="primary-btn" onClick={()=>setModal({type:'task',defaults:{due_date:today}})}><Plus size={18}/> Add a task</button></section>
        <div className="home-layout"><div className="home-main"><section className="paper feature"><div className="tape tape-left"/><div className="section-top"><div><span className="eyebrow">WEEKLY CLASS NOTES</span><h2>{day===today?'Today’s classes':`Classes · ${niceDate(day)}`}</h2></div><div className="date-steppers"><button aria-label="Previous day" onClick={()=>setDay(nextDay(day,-1))}><ChevronLeft size={18}/></button><button onClick={()=>setDay(today)}>Today</button><button aria-label="Next day" onClick={()=>setDay(nextDay(day))}><ChevronRight size={18}/></button></div></div>
          {groupedSchedule.some(group=>group.day_of_week===thisDay)?
            <div className="class-list">{groupedSchedule.filter(group=>group.day_of_week===thisDay).map(group=><ClassGroupRow key={group.key} group={group} course={courses[group.course_id]} onEdit={()=>setModal({type:'classGroup',group,course:courses[group.course_id]})}/>)}</div>:
            <div className="empty-note">No classes on this day. A little breathing room.</div>}</section>
          <div className="day-columns">{[today,nextDay(today)].map((k,index)=><section className="paper task-paper" key={k}><div className="section-top"><div><span className="eyebrow">{index?'LOOKING AHEAD':'YOUR CHECKLIST'}</span><h2>{index?'Tomorrow':'Today'} <span className="muted-date">{niceDate(k)}</span></h2></div><button className="round-add" aria-label={`Add task for ${index?'tomorrow':'today'}`} onClick={()=>setModal({type:'task',defaults:{due_date:k}})}><Plus size={18}/></button></div><DayItems k={k} tasks={tasksFor(k)} events={eventsFor(k)} courses={courses} toggle={toggle} edit={(type,item)=>setModal({type,item})}/></section>)}</div>
        </div><aside className="home-side"><section className="paper up-next"><Sparkles className="sticker" size={24}/><span className="eyebrow">ON THE HORIZON</span><h2>Coming up soon</h2>{upcoming.length?upcoming.map(e=><button className="upcoming-item" key={e.id} onClick={()=>setModal({type:'event',item:e})}><div className="event-icon">{e.kind==='exam'?<GraduationCap size={17}/>:<CalendarDays size={17}/>}</div><span><strong>{e.title}</strong><small>{niceDate(malaysiaDate(e.starts_at))} · {malaysiaInput(e.starts_at).slice(11)}</small><b>{countdown(e.starts_at,now)}</b></span></button>):<div className="empty-note">No upcoming meetings or exams yet.</div>}<button className="text-link" onClick={()=>setTab('planner')}>Open planner <ChevronRight size={16}/></button></section>
          <section className="paper quick-card"><span className="eyebrow">QUICK ADD</span><h2>Put it on paper</h2><button onClick={()=>setModal({type:'event',defaults:{kind:'exam'}})}><GraduationCap size={17}/> Exam <Plus size={16}/></button><button onClick={()=>setModal({type:'event',defaults:{kind:'meeting'}})}><CalendarDays size={17}/> Meeting <Plus size={16}/></button><button onClick={()=>setModal({type:'task',defaults:{kind:'assignment'}})}><ClipboardList size={17}/> Assignment <Plus size={16}/></button></section></aside></div></>}
      {tab==='week'&&<><Heading eyebrow="YOUR WEEK AT A GLANCE" title="Class timetable" text="One card per course and day. Open a card to edit its class times or group options." action={<button className="primary-btn" onClick={()=>setModal({type:'class'})}><Plus size={18}/> Add class</button>}/><div className="week-grid">{weekdays.map((name,i)=>({name,day:i+1})).filter(({day})=>day<=5||groupedSchedule.some(group=>group.day_of_week===day)).map(({name,day})=><section className="paper week-day" key={name}><div className="week-head"><span>{name.slice(0,3).toUpperCase()}</span><strong>{name}</strong><small>{groupedSchedule.filter(group=>group.day_of_week===day).length} courses</small></div>{groupedSchedule.filter(group=>group.day_of_week===day).map(group=><button key={group.key} className="week-class" style={{'--course-color':tone(courses[group.course_id])}} onClick={()=>setModal({type:'classGroup',group,course:courses[group.course_id]})}><span className="week-course-code">{courses[group.course_id]?.code||'Course'}</span><strong>{courses[group.course_id]?.name||'Course'}</strong><span className="week-slots">{distinctSlots(group.items).map(slot=><span className="week-slot" key={`${slot.start_time}-${slot.end_time}-${slot.venue}`}><Clock size={13}/><span>{formatTime(slot.start_time)} – {formatTime(slot.end_time)}<small>{slot.venue}{slot.notes.length?` · ${slot.notes.join(' / ')}`:''}</small></span></span>)}</span></button>)}{!groupedSchedule.some(group=>group.day_of_week===day)&&<p className="quiet">No classes</p>}</section>)}</div></>}
      {tab==='courses'&&<><Heading eyebrow="SUBJECTS & TO-DOS" title="Your courses" text="Keep a separate checklist for each course." action={<button className="primary-btn" onClick={()=>setModal({type:'course'})}><Plus size={18}/> Add course</button>}/><div className="course-grid">{data.courses.map(c=>{const ts=data.tasks.filter(t=>t.course_id===c.id).sort((a,b)=>a.due_date.localeCompare(b.due_date));return <section className="paper course-card" key={c.id} style={{'--course-color':c.color}}><div className="course-head"><span className="course-code">{c.code}</span><button className="icon-button" title="Edit course" onClick={()=>setModal({type:'course',item:c})}><Pencil size={16}/></button></div><h2>{c.name}</h2><div className="course-progress">{ts.filter(t=>t.completed).length} of {ts.length} complete</div><div className="course-tasks">{ts.length?ts.map(t=><TaskLine key={t.id} task={t} course={c} onToggle={()=>toggle('tasks',t)} onEdit={()=>setModal({type:'task',item:t})}/>):<p className="quiet">No tasks yet. Start with one small step.</p>}</div><button className="add-line" onClick={()=>setModal({type:'task',defaults:{course_id:c.id}})}><Plus size={16}/> Add course task</button></section>})}</div></>}
      {tab==='year'&&<><Heading eyebrow="THE BIG PICTURE" title="Academic calendar" text="Weekends and holidays are marked across the 2026 and 2027 calendars."/><div className="year-tabs"><button className={year===2026?'selected':''} onClick={()=>setYear(2026)}>2026</button><button className={year===2027?'selected':''} onClick={()=>setYear(2027)}>2027</button></div><div className="year-key"><span><i className="legend-holiday"/>Public holiday</span><span><i className="legend-weekend"/>Weekend</span><span><i className="legend-term"/>Semester</span><small>Holiday dates follow the supplied XMUM calendars and may change.</small></div><div className="year-layout"><div><div className="term-list">{academicYears[year].terms.map(t=><div className="term-chip" key={t.name} style={{'--course-color':t.color}}><span className="term-spot"/><strong>{t.name}</strong><small>{niceDate(t.start)} – {niceDate(t.end)}</small></div>)}</div><div className="months-grid">{Array.from({length:12},(_,m)=><Month key={`${year}-${m}`} year={year} month={m} info={academicYears[year]}/>)}</div></div><aside className="paper official-card"><span className="eyebrow">OFFICIAL UNIVERSITY CALENDAR</span><h2>{year} at a glance</h2><p>Registration, revision, exams and breaks are marked on the original.</p><a href={academicYears[year].image} target="_blank" rel="noreferrer"><img src={academicYears[year].image} alt={`Xiamen University Malaysia undergraduate academic calendar ${year}`}/><span>Open full-size calendar <ExternalLink size={15}/></span></a><div className="key-dates"><h3>Academic dates</h3>{academicYears[year].milestones.map(([label,start,end])=><div key={label}><b>{label}</b><small>{niceDate(start)}{start!==end?` – ${niceDate(end)}`:''}</small></div>)}</div></aside></div></>}
      {tab==='planner'&&<><Heading eyebrow="DATES WORTH REMEMBERING" title="Planner & deadlines" text="Meetings and exams appear on their day’s checklist. Assignments have their own due dates." action={<div className="heading-actions"><button className="secondary-btn" onClick={()=>setModal({type:'task',defaults:{kind:'assignment'}})}><Plus size={17}/> Assignment</button><button className="primary-btn" onClick={()=>setModal({type:'event'})}><Plus size={17}/> Meeting or exam</button></div>}/><div className="planner-grid"><section className="paper planner-paper"><div className="section-top"><h2>Meetings & exams</h2><CalendarDays size={19}/></div>{data.events.slice().sort((a,b)=>a.starts_at.localeCompare(b.starts_at)).length?data.events.slice().sort((a,b)=>a.starts_at.localeCompare(b.starts_at)).map(e=><div className={`planner-item ${e.completed?'done':''}`} key={e.id}><button className="check" aria-label="Mark event done" onClick={()=>toggle('events',e)}>{e.completed&&<Check size={15}/>}</button><div><span className="type-label">{e.kind}</span><strong>{e.title}</strong><small>{niceDate(malaysiaDate(e.starts_at))} at {malaysiaInput(e.starts_at).slice(11)} · {e.venue||'No venue'}</small>{e.notes&&<p>{e.notes}</p>}{!e.completed&&new Date(e.starts_at).getTime()>now&&<b className="countdown">{countdown(e.starts_at,now)}</b>}</div><button className="icon-button" title="Edit" onClick={()=>setModal({type:'event',item:e})}><Pencil size={16}/></button></div>):<p className="empty-note">Add a meeting or exam to see it here.</p>}</section><section className="paper planner-paper"><div className="section-top"><h2>Assignments</h2><ClipboardList size={19}/></div>{data.tasks.filter(t=>t.kind==='assignment').sort((a,b)=>a.due_date.localeCompare(b.due_date)).length?data.tasks.filter(t=>t.kind==='assignment').sort((a,b)=>a.due_date.localeCompare(b.due_date)).map(t=><TaskLine key={t.id} task={t} course={courses[t.course_id]} onToggle={()=>toggle('tasks',t)} onEdit={()=>setModal({type:'task',item:t})} detail/>):<p className="empty-note">No assignments added yet.</p>}</section></div>{'Notification' in window&&<button className="notification-action" onClick={async()=>{const p=await Notification.requestPermission();flash(p==='granted'?'On-device alerts enabled while the organizer is open.':'On-device alerts were not enabled.')}}><Bell size={17}/> Enable on-device alerts while open</button>}</>}
    </main>{modal&&(modal.type==='classGroup'?<ClassGroupDialog group={modal.group} course={modal.course} onClose={()=>setModal(null)} onEdit={item=>setModal({type:'class',item})}/>:<Editor key={`${modal.type}-${modal.item?.id||'new'}`} modal={modal} courses={data.courses} onClose={()=>setModal(null)} onSave={save} onDelete={remove} busy={busy}/>)}</div>;
}

function Heading({eyebrow,title,text,action}){return <section className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{text}</p></div>{action}</section>}
function ClassGroupRow({group,course,onEdit}){const slots=distinctSlots(group.items);return <button className="class-row" onClick={onEdit}><span className="class-color" style={{background:tone(course)}}/><span className="class-info"><strong>{course?.name||'Course'}</strong><small>{course?.code} · {slots.length} {slots.length===1?'time':'times'}</small><span className="class-slot-preview">{slots.map(slot=><span key={`${slot.start_time}-${slot.venue}`}>{formatTime(slot.start_time)}–{formatTime(slot.end_time)} · {slot.venue}{slot.notes.length?` · ${slot.notes.join(' / ')}`:''}</span>)}</span></span><ChevronRight size={17} className="row-pencil"/></button>}
function ClassGroupDialog({group,course,onClose,onEdit}){return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="dialog" role="dialog" aria-modal="true" aria-label={`${course?.name||'Course'} class times`}><div className="dialog-head"><div><span className="eyebrow">{weekdays[group.day_of_week-1]?.toUpperCase()}</span><h2>{course?.name||'Class times'}</h2></div><button className="icon-button" aria-label="Close" onClick={onClose}><X size={21}/></button></div><p className="group-help">Select a time to edit or remove it. Alternative rooms remain separate so you can keep the correct group.</p>{group.items.map(item=><button key={item.id} className="group-option" onClick={()=>onEdit(item)}><Clock size={17}/><span><strong>{formatTime(item.start_time)} – {formatTime(item.end_time)}</strong><small>{item.venue}{item.note?` · ${item.note}`:''}</small></span><Pencil size={16}/></button>)}</div></div>}
function TaskLine({task,course,onToggle,onEdit,detail}){return <div className={`task-line ${task.completed?'done':''}`}><button className="check" onClick={onToggle} aria-label={task.completed?'Mark incomplete':'Mark complete'}>{task.completed&&<Check size={15}/>}</button><button className="task-click" onClick={onEdit}><strong>{task.title}</strong><small>{course&&<span className="mini-course" style={{background:tone(course)}}>{course.code}</span>} {detail&&niceDate(task.due_date)}{task.notes&&` · ${task.notes}`}</small></button><button className="edit-mini" title="Edit task" onClick={onEdit}><Pencil size={14}/></button></div>}
function DayItems({k,tasks,events,courses,toggle,edit}){return <div className="day-items">{!tasks.length&&!events.length&&<p className="empty-note">Nothing due. Add something when you’re ready.</p>}{events.map(e=><div className={`task-line event-line ${e.completed?'done':''}`} key={e.id}><button className="check" onClick={()=>toggle('events',e)} aria-label="Mark event done">{e.completed&&<Check size={15}/>}</button><button className="task-click" onClick={()=>edit('event',e)}><strong>{e.title}</strong><small>{e.kind} · {malaysiaInput(e.starts_at).slice(11)} {e.venue&&`· ${e.venue}`}</small></button></div>)}{tasks.map(t=><TaskLine key={t.id} task={t} course={courses[t.course_id]} onToggle={()=>toggle('tasks',t)} onEdit={()=>edit('task',t)}/>)}</div>}
export function Month({year,month,info}){
 const first=new Date(Date.UTC(year,month,1));const length=new Date(Date.UTC(year,month+1,0)).getUTCDate();const start=first.getUTCDay();
 const monthStart=`${year}-${String(month+1).padStart(2,'0')}-01`,monthEnd=`${year}-${String(month+1).padStart(2,'0')}-${String(length).padStart(2,'0')}`;
 const monthHolidays=info.holidays.filter(([from,to])=>from<=monthEnd&&to>=monthStart);
 return <div className="paper month"><h3>{new Intl.DateTimeFormat('en-MY',{month:'long',timeZone:'UTC'}).format(first)}</h3><div className="month-grid">{['S','M','T','W','T','F','S'].map((d,i)=><span className={`dow ${i===0||i===6?'weekend-heading':''}`} key={i}>{d}</span>)}{Array.from({length:start},(_,i)=><span key={`blank-${i}`}/>)}{Array.from({length},(_,i)=>{
  const key=`${year}-${String(month+1).padStart(2,'0')}-${String(i+1).padStart(2,'0')}`;
  const term=info.terms.find(t=>key>=t.start&&key<=t.end);
  const weekend=(start+i)%7===0||(start+i)%7===6;
  const holidays=monthHolidays.filter(([from,to])=>key>=from&&key<=to).map(([, ,label])=>label);
  return <span key={key} className={`month-day ${term?'in-term':''} ${weekend?'is-weekend':''} ${holidays.length?'is-holiday':''} ${key===dateKey()?'is-today':''}`} style={{'--term-color':term?.color}} title={[niceDate(key),...holidays,weekend?'Weekend':'',term?.name||''].filter(Boolean).join(' · ')} aria-label={[niceDate(key),...holidays,weekend?'Weekend':''].filter(Boolean).join(', ')}>{i+1}</span>})}</div>{monthHolidays.length>0&&<div className="month-holidays">{monthHolidays.map(([from,to,label])=><div key={`${from}-${label}`}><span className="holiday-marker"/><span>{label}</span><small>{from===to?new Date(from+'T12:00:00Z').getUTCDate():`${new Date(from+'T12:00:00Z').getUTCDate()}–${new Date(to+'T12:00:00Z').getUTCDate()}`}</small></div>)}</div>}</div>
}

 function Editor({modal,courses,onClose,onSave,onDelete,busy}){const {type,item,defaults={}}=modal;
 const [f,setF]=useState(()=>{if(type==='task')return {title:'',kind:'task',due_date:dateKey(),course_id:'',notes:'',...defaults,...item};if(type==='event')return {title:'',kind:'meeting',course_id:'',venue:'',notes:'',...defaults,...item,starts_at:item?malaysiaInput(item.starts_at):`${dateKey()}T09:00`};if(type==='class')return {course_id:courses[0]?.id||'',day_of_week:1,start_time:'09:00',end_time:'10:00',venue:'',note:'',...item};return {code:'',name:'',color:'#c9e4f7',...item}});
 const update=(field,value)=>setF(old=>({...old,[field]:value}));
 const submit=e=>{e.preventDefault();let values;if(type==='task')values={title:f.title.trim(),kind:f.kind,due_date:f.due_date,course_id:f.course_id||null,notes:f.notes||'',completed:!!f.completed};
 else if(type==='event'){const instant=new Date(`${f.starts_at}+08:00`);if(Number.isNaN(instant.getTime()))return;values={title:f.title.trim(),kind:f.kind,starts_at:instant.toISOString(),course_id:f.course_id||null,venue:f.venue||'',notes:f.notes||'',completed:!!f.completed};}
 else if(type==='class')values={course_id:f.course_id,day_of_week:Number(f.day_of_week),start_time:f.start_time,end_time:f.end_time,venue:f.venue||'',note:f.note||''};
 else values={code:f.code.trim().toUpperCase(),name:f.name.trim(),color:f.color};onSave(type==='class'?'class_sessions':type==='task'?'tasks':type==='event'?'events':'courses',values,item?.id)};
 const field=(name,label,kind='text',props={})=><label className="field"><span>{label}</span><input type={kind} value={f[name]??''} onChange={e=>update(name,e.target.value)} required={['title','name','code','due_date','starts_at','course_id'].includes(name)&&!(name==='course_id'&&type!=='class')} {...props}/></label>;
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="dialog" role="dialog" aria-modal="true" aria-label={`${item?'Edit':'Add'} ${type}`}><div className="dialog-head"><div><span className="eyebrow">{item?'MAKE A CHANGE':'SOMETHING NEW'}</span><h2>{item?'Edit':'Add'} {type==='class'?'class':type}</h2></div><button className="icon-button" aria-label="Close" onClick={onClose}><X size={21}/></button></div><form onSubmit={submit}>
 {type==='course'&&<>{field('code','Course code')}{field('name','Course name')}{field('color','Card color','color')}</>}
 {(type==='task'||type==='event')&&<>{field('title',type==='task'?'What needs doing?':'Name')}
 <label className="field"><span>Type</span><select value={f.kind} onChange={e=>update('kind',e.target.value)}>{(type==='task'?['task','assignment']:['meeting','exam']).map(k=><option key={k} value={k}>{k[0].toUpperCase()+k.slice(1)}</option>)}</select></label></>}
 {type!=='course'&&<label className="field"><span>Course {type==='class'?'':'(optional)'}</span><select value={f.course_id||''} required={type==='class'} onChange={e=>update('course_id',e.target.value)}><option value="">{type==='class'?'Choose a course':'No course'}</option>{courses.map(c=><option key={c.id} value={c.id}>{c.code} · {c.name}</option>)}</select></label>}
 {type==='task'&&<>{field('due_date',f.kind==='assignment'?'Deadline':'Day','date')}<label className="field"><span>Notes (optional)</span><textarea value={f.notes||''} onChange={e=>update('notes',e.target.value)} rows="3"/></label></>}
 {type==='event'&&<>{field('starts_at','Date and time (Malaysia)','datetime-local')}{field('venue','Venue (optional)')}<label className="field"><span>Notes (optional)</span><textarea value={f.notes||''} onChange={e=>update('notes',e.target.value)} rows="3"/></label><p className="form-hint"><Mail size={15}/> Email reminders: 14, 7, 3, 2, 1 days before, then hourly for the last 24 hours.</p></>}
 {type==='class'&&<><label className="field"><span>Day</span><select value={f.day_of_week} onChange={e=>update('day_of_week',e.target.value)}>{weekdays.map((d,i)=><option value={i+1} key={d}>{d}</option>)}</select></label><div className="form-row">{field('start_time','Starts','time')}{field('end_time','Ends','time')}</div>{field('venue','Room / venue')} {field('note','Weeks or group note')}</>}
 <div className="dialog-actions">{item&&<button type="button" className="delete-btn" onClick={()=>{onDelete(type==='class'?'class_sessions':type==='task'?'tasks':type==='event'?'events':'courses',item);onClose()}}><Trash2 size={17}/> Delete</button>}<button type="button" className="secondary-btn" onClick={onClose}>Cancel</button><button className="primary-btn" disabled={busy} type="submit"><Check size={17}/> Save</button></div></form></div></div>}

function Auth({onMessage,message,theme,onToggleTheme}){const [mode,setMode]=useState('signin'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e){e.preventDefault();setBusy(true);try{const {error}=mode==='signup'?await db.auth.signUp({email,password}):await db.auth.signInWithPassword({email,password});if(error)throw error;if(mode==='signup')onMessage('Account created. Check your email if confirmation is enabled.');}catch(e){onMessage(e.message)}finally{setBusy(false)}}
 return <div className="auth-screen"><button className="icon-button auth-theme" onClick={onToggleTheme} aria-label={`Switch to ${theme==='dark'?'light':'dark'} mode`}>{theme==='dark'?<Sun size={20}/>:<Moon size={20}/>}</button><div className="auth-card paper"><div className="tape tape-left"/><div className="auth-icon"><BookOpen size={29}/></div><div className="eyebrow">YOUR OWN LITTLE SPACE</div><h1>Welcome to <em>paper plan.</em></h1><p>Classes, plans, and deadlines in one calm place.</p><form onSubmit={submit}><label className="field"><span>Email</span><input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="field"><span>Password</span><input type="password" required minLength="6" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary-btn auth-submit" disabled={busy}>{mode==='signup'?'Create account':'Sign in'}</button></form><button className="auth-switch" onClick={()=>setMode(mode==='signin'?'signup':'signin')}>{mode==='signin'?'New here? Create an account':'Already have an account? Sign in'}</button>{message&&<p role="status" className="auth-message">{message}</p>}</div></div>}
